server:
    port: ${PORT:10000}
    address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:mem:strava
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-muddy-union-zagwinxy-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_l1t7kVjqiFYe}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          provider_disables_autocommit: true
        lob:
          non_contextual_creation: true